-- Domains for pizza ordering app (Firebird 5.0)
CREATE DOMAIN DM_NAME      AS VARCHAR(100) CHARACTER SET UTF8 NOT NULL;
CREATE DOMAIN DM_PHONE     AS VARCHAR(32)  CHARACTER SET UTF8;
CREATE DOMAIN DM_EMAIL     AS VARCHAR(255) CHARACTER SET UTF8;
CREATE DOMAIN DM_PRICE     AS DECIMAL(10,2) DEFAULT 0.00 NOT NULL;
CREATE DOMAIN DM_QTY       AS INTEGER DEFAULT 1 NOT NULL;
CREATE DOMAIN DM_STATUS    AS VARCHAR(20)  CHARACTER SET UTF8 DEFAULT 'NEW' NOT NULL;
CREATE DOMAIN DM_GUID      AS VARCHAR(36)  CHARACTER SET UTF8;