-- Exceptions
CREATE EXCEPTION EX_PIZZA_NOT_FOUND 'Pizza not found';
CREATE EXCEPTION EX_CUSTOMER_NOT_FOUND 'Customer not found';

-- Procedure to place a single-line order (inserts ORDERS + one ORDER_ITEMS)
-- Returns generated order id
SET TERM ^ ;
CREATE PROCEDURE SP_PLACE_ORDER (
  P_CUSTOMER_ID INTEGER,
  P_PIZZA_ID    INTEGER,
  P_QUANTITY    INTEGER
)
RETURNS (
  O_ORDER_ID INTEGER
)
AS
DECLARE VARIABLE V_UNIT_PRICE DECIMAL(10,2);
DECLARE VARIABLE V_TOTAL      DECIMAL(12,2);
BEGIN
  -- Validate customer
  IF ( (SELECT COUNT(*) FROM CUSTOMERS WHERE ID = :P_CUSTOMER_ID) = 0 ) THEN
    EXCEPTION EX_CUSTOMER_NOT_FOUND USING ('Customer not found');

  -- Normalize quantity
  IF (P_QUANTITY IS NULL OR P_QUANTITY <= 0) THEN
    P_QUANTITY = 1;

  -- Get pizza price
  SELECT PRICE FROM PIZZAS WHERE ID = :P_PIZZA_ID INTO :V_UNIT_PRICE;
  IF (V_UNIT_PRICE IS NULL) THEN
    EXCEPTION EX_PIZZA_NOT_FOUND USING ('Pizza not found');

  V_TOTAL = V_UNIT_PRICE * P_QUANTITY;

  -- Insert order header and return id
  INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_PRICE, STATUS)
    VALUES (:P_CUSTOMER_ID, CURRENT_TIMESTAMP, :V_TOTAL, 'NEW')
    RETURNING ID INTO :O_ORDER_ID;

  -- Insert order item
  INSERT INTO ORDER_ITEMS (ORDER_ID, PIZZA_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL)
    VALUES (:O_ORDER_ID, :P_PIZZA_ID, :P_QUANTITY, :V_UNIT_PRICE, :V_TOTAL);

  -- Return single-row result with the new order id
  SUSPEND;
END
^
SET TERM ; ^

-- Selectable procedure to fetch order details (header + line items)
SET TERM ^ ;
CREATE PROCEDURE SP_GET_ORDER_DETAILS (
  P_ORDER_ID INTEGER
)
RETURNS (
  ORDER_ID    INTEGER,
  ORDER_DATE  TIMESTAMP,
  CUSTOMER_ID INTEGER,
  CUSTOMER_NAME VARCHAR(100) CHARACTER SET UTF8,
  ITEM_ID     INTEGER,
  PIZZA_ID    INTEGER,
  PIZZA_NAME  VARCHAR(100) CHARACTER SET UTF8,
  QUANTITY    INTEGER,
  UNIT_PRICE  DECIMAL(10,2),
  LINE_TOTAL  DECIMAL(12,2)
)
AS
BEGIN
  FOR
    SELECT o.ID, o.ORDER_DATE, o.CUSTOMER_ID, c.NAME, i.ID, i.PIZZA_ID, p.NAME, i.QUANTITY, i.UNIT_PRICE, i.LINE_TOTAL
    FROM ORDERS o
    JOIN CUSTOMERS c ON c.ID = o.CUSTOMER_ID
    JOIN ORDER_ITEMS i ON i.ORDER_ID = o.ID
    JOIN PIZZAS p ON p.ID = i.PIZZA_ID
    WHERE o.ID = :P_ORDER_ID
    INTO :ORDER_ID, :ORDER_DATE, :CUSTOMER_ID, :CUSTOMER_NAME, :ITEM_ID, :PIZZA_ID, :PIZZA_NAME, :QUANTITY, :UNIT_PRICE, :LINE_TOTAL
  DO
  BEGIN
    SUSPEND;
  END
END
^
SET TERM ; ^