-- =================================================
-- DOMAINS
-- =================================================
-- Domain: DMEMAIL
CREATE DOMAIN DMEMAIL AS VARCHAR(255) CHARACTER SET UTF8;
-- Domain: "DM_EMAIL"
CREATE DOMAIN "DM_EMAIL" AS VARCHAR(255) CHARACTER SET UTF8;
-- Domain: "DM_GUID"
CREATE DOMAIN "DM_GUID" AS VARCHAR(36) CHARACTER SET UTF8;
-- Domain: "DM_NAME"
CREATE DOMAIN "DM_NAME" AS VARCHAR(100) CHARACTER SET UTF8;
-- Domain: "DM_PHONE"
CREATE DOMAIN "DM_PHONE" AS VARCHAR(32) CHARACTER SET UTF8;
-- Domain: "DM_PRICE"
CREATE DOMAIN "DM_PRICE" AS DECIMAL(10,2) DEFAULT 0.00;
-- Domain: "DM_QTY"
CREATE DOMAIN "DM_QTY" AS INTEGER DEFAULT 1;
-- Domain: "DM_STATUS"
CREATE DOMAIN "DM_STATUS" AS VARCHAR(20) CHARACTER SET UTF8 DEFAULT 'NEW';
-- Domain: EMAIL
CREATE DOMAIN EMAIL AS VARCHAR(255) CHARACTER SET UTF8;

-- =================================================
-- EXCEPTIONS
-- =================================================
-- Exception: "EX_CUSTOMER_NOT_FOUND"
CREATE EXCEPTION "EX_CUSTOMER_NOT_FOUND" 'Customer not found';
-- Exception: "EX_PIZZA_NOT_FOUND"
CREATE EXCEPTION "EX_PIZZA_NOT_FOUND" 'Pizza not found';

-- =================================================
-- TABLES
-- =================================================
-- Table: CUSTOMERS
CREATE TABLE CUSTOMERS (
  ID INTEGER,
  NAME "DM_NAME",
  PHONE "DM_PHONE",
  EMAIL "DM_EMAIL",
  "CREATED_AT" TIMESTAMP
);

-- Table: ORDERS
CREATE TABLE ORDERS (
  ID INTEGER,
  "CUSTOMER_ID" INTEGER,
  "ORDER_DATE" TIMESTAMP,
  "TOTAL_PRICE" DECIMAL(12,2),
  STATUS "DM_STATUS" DEFAULT 'NEW'
);

-- Table: "ORDER_ITEMS"
CREATE TABLE "ORDER_ITEMS" (
  ID INTEGER,
  "ORDER_ID" INTEGER,
  "PIZZA_ID" INTEGER,
  QUANTITY "DM_QTY" DEFAULT 1,
  "UNIT_PRICE" "DM_PRICE" DEFAULT 0.00,
  "LINE_TOTAL" DECIMAL(12,2)
);

-- Table: PIZZAS
CREATE TABLE PIZZAS (
  ID INTEGER,
  CODE VARCHAR(20) CHARACTER SET UTF8,
  NAME "DM_NAME",
  DESCRIPTION VARCHAR(1024) CHARACTER SET UTF8,
  PRICE "DM_PRICE" DEFAULT 0.00,
  "IS_ACTIVE" SMALLINT
);


-- =================================================
-- PROCEDURES
-- =================================================
SET TERM ^ ;
-- Procedure: "SP_GET_ORDER_DETAILS"
CREATE PROCEDURE "SP_GET_ORDER_DETAILS"
(
  "P_ORDER_ID" INTEGER
)
RETURNS
(
  "ORDER_ID" INTEGER,
  "ORDER_DATE" TIMESTAMP,
  "CUSTOMER_ID" INTEGER,
  "CUSTOMER_NAME" VARCHAR(100) CHARACTER SET UTF8,
  "ITEM_ID" INTEGER,
  "PIZZA_ID" INTEGER,
  "PIZZA_NAME" VARCHAR(100) CHARACTER SET UTF8,
  QUANTITY INTEGER,
  "UNIT_PRICE" DECIMAL(10,2),
  "LINE_TOTAL" DECIMAL(12,2)
)
AS
BEGIN
  FOR
    SELECT o.ID, o.ORDER_DATE, o.CUSTOMER_ID, c.NAME, i.ID, i.PIZZA_ID, p.NAME, i.QUANTITY, i.UNIT_PRICE, i.LINE_TOTAL
    FROM ORDERS o
    JOIN CUSTOMERS c ON c.ID = o.CUSTOMER_ID
    JOIN ORDER_ITEMS i ON i.ORDER_ID = o.ID
    JOIN PIZZAS p ON p.ID = i.PIZZA_ID
    WHERE o.ID = :P_ORDER_ID
    INTO :ORDER_ID, :ORDER_DATE, :CUSTOMER_ID, :CUSTOMER_NAME, :ITEM_ID, :PIZZA_ID, :PIZZA_NAME, :QUANTITY, :UNIT_PRICE, :LINE_TOTAL
  DO
  BEGIN
    SUSPEND;
  END
END
^

-- Procedure: "SP_PLACE_ORDER"
CREATE PROCEDURE "SP_PLACE_ORDER"
(
  "P_CUSTOMER_ID" INTEGER,
  "P_PIZZA_ID" INTEGER,
  "P_QUANTITY" INTEGER
)
RETURNS
(
  "O_ORDER_ID" INTEGER
)
AS
DECLARE VARIABLE V_UNIT_PRICE DECIMAL(10,2);
DECLARE VARIABLE V_TOTAL      DECIMAL(12,2);
BEGIN
  -- Validate customer
  IF ( (SELECT COUNT(*) FROM CUSTOMERS WHERE ID = :P_CUSTOMER_ID) = 0 ) THEN
    EXCEPTION EX_CUSTOMER_NOT_FOUND USING ('Customer not found');

  -- Normalize quantity
  IF (P_QUANTITY IS NULL OR P_QUANTITY <= 0) THEN
    P_QUANTITY = 1;

  -- Get pizza price
  SELECT PRICE FROM PIZZAS WHERE ID = :P_PIZZA_ID INTO :V_UNIT_PRICE;
  IF (V_UNIT_PRICE IS NULL) THEN
    EXCEPTION EX_PIZZA_NOT_FOUND USING ('Pizza not found');

  V_TOTAL = V_UNIT_PRICE * P_QUANTITY;

  -- Insert order header and return id
  INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_PRICE, STATUS)
    VALUES (:P_CUSTOMER_ID, CURRENT_TIMESTAMP, :V_TOTAL, 'NEW')
    RETURNING ID INTO :O_ORDER_ID;

  -- Insert order item
  INSERT INTO ORDER_ITEMS (ORDER_ID, PIZZA_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL)
    VALUES (:O_ORDER_ID, :P_PIZZA_ID, :P_QUANTITY, :V_UNIT_PRICE, :V_TOTAL);

  -- Return single-row result with the new order id
  SUSPEND;
END
^

SET TERM ; ^

